### ISSUE TITLE
Allow for self closing tags to not be closed

### ISSUE THREAD

**Issue by adamfortuna** [codeschool/htmlTagValidator#1]
Both of the following will work:

```
<link src='test.html'>
``` 

```
<link src='test.html' />
``` 

We should probably allow for either, depending on the mode that's set. What about a `strict` mode which will check this kind of thing, but allow for non-self closing tags?

**Comment by nwronski** [comment]
As of version 1.0.x the parser now allows for either format. This will possibly become a setting you can toggle on/off in the options object in the future.
