### ISSUE TITLE
Ability to run validator synchronously?

### ISSUE THREAD

**Issue by faceleg** [codeschool/htmlTagValidator#10]
I'm trying to integrate HTML validation into my unit test set.

I am walking the my project's file tree synchronously and validating any html files I find.

Given how most of the JS testing libraries work, it would be easier if there was a way to make the html tag validator run synchronously.

Is this possible with the current build?

**Comment by nwronski** [comment]
Apologies, this is fixed with 3a7077f7a074c4dd42a5bb92d65083d235b50890 and published to npm as `html-tag-validator@1.1.0`.
