### ISSUE TITLE
Rejects PHP Short Tags

### ISSUE THREAD

**Issue by aj-foster** [codeschool/htmlTagValidator#17]
Although short tags have every reason to be rejected, it still causes some issues during validation. Consider the following:

`<li><? echo $variable; ?></li>`

The validator responds, "`li` is not a valid self closing tag." Similar for `<?= ?>` as well. The more civilized older brother, `<?php ?>`, works fine.

**Comment by renz45** [comment]
This should be fixed with the above commit.
