### ISSUE TITLE
Multiple entities in a attribute detected as invalid

### ISSUE THREAD

**Issue by AllanJard** [codeschool/htmlTagValidator#33]
Consider the string:

```
<p>This is a link: <a data-saferedirecturl="https://www.google.com/url?q=http://.../&amp;source=gmail&amp;ust=...&amp;usg=...">Link</a></p>
```

I would expect that to parse correctly, however the entity disallow [here](https://github.com/pluralsight/htmlTagValidator/blob/d5b6cf7d42c6d088b9d15339e647adadc462470e/src/html-grammar.pegjs#L539) is greedy and so sees `&amp;source=gmail&amp;ust=...&amp;` which it rightly rejects.

The fix would be to make it lazy: `/&([\S]+?);/g;`. However, that said, it looks like that while look might just infinite loop to me since it is never changing the value of `i.value`.

Is this repo still being maintained? I'd be happy to submit a PR for a fix it so. If it isn't, can you mark the repo as no longer maintained and perhaps suggest some alternatives?

**Comment by aj-foster** [comment]
Hi @AllanJard 👋🏼 

Thank you for filing this issue. We haven't maintained this repo in a while so I'm going to transition it to an archived state. I encourage everyone to find (or make!) forks of the code.

Thank you for your support!
