### ISSUE TITLE
Options to allow <span> without `property` attribute

### ISSUE THREAD

**Issue by faceleg** [codeschool/htmlTagValidator#9]
Is it possible to configure this module to allow "required" attributes to be missing?

I have some legacy code I'm testing with and would like to turn some "required" attributes off.

**Comment by nwronski** [comment]
Not now, but soon! We're planning to add this feature in the 1.1.x release. You can check in on the progress in the [milestones](https://github.com/codeschool/htmlTagValidator/blob/master/todo.md).

**Comment by faceleg** [comment]
Wow excellent documentation, thanks!

You may be interested in this: https://github.com/solnetdigital/testing-html, I've used this module to allow unit testing of a project's HTML. Great fun!

**Comment by nwronski** [comment]
Will have to update the documentation when this feature is complete. But, working off the latest `master` branch (unreleased on npm), you should be able to use the following`options` to override the list of allowed tag attributes: 
  - using `'policy': 'replace'` in `settings` 
  - using a global override to allow anything `'_': { 'mixed': '*' }` in `attributes`

Here is an example:

``` javascript
var htmlTagValidator = require('html-tag-validator'),
  sampleHtml = "<html>" +
               "<head><title NotAnAttribute="notvalid">hello world</title></head>" +
               "<body><p>my cool page</p></body>" +
               "</html>";

htmlTagValidator(sampleHtml, {
  'settings': {
    'policy': 'replace'
  },
  'attributes': {
    '_': {
      'mixed': '*'
    }
  }
}, function (err, ast) {
  if (err) {
    throw err;
  } else {
    console.log(ast);
  }
});
```

**Comment by faceleg** [comment]
Love your work, thanks!
